package com.tuckshopspotter.providers;

import android.database.sqlite.SQLiteDatabase;

/**
 * Created by CodeTribe on 2015-03-14.
 */
public class TuckShopTable {

    public static final String SHOP_TABLE_NAME = "shops";
    public static final String COLUMN_SHOP_NAME = "shopname";
    public static final String COLUMN_INVENTORY_NAME = "inventory";
    public static final String COLUMN_SHOP_ID = "shopID"; //This is the global ID
    public static final String COLUMN_CP_SHOP_ID = "_ID"; //this is 'local' ID generated by CP
    public static final String COLUMN_lONGITUDE ="longitude";
    public static final String COLUMN_LATITUDE ="latitude";

    public static final String COLUMN_AIRTIME = "airtime";
//    public static final String COLUMN_CP_INVENTORY_ID = "_ID"; //this is 'local' ID generated by CP
//    public static final String COLUMN_ELECTRIC = "electric";
//    public static final String COLUMN_INTERNET = "internetCafe";
//    public static final String COLUMN_SHOPID = "internetCafe";


    public static final String DEFAULT_SORT_ORDER = "_ID Desc";

    public static final String[] DEFAULT_SHOPS_PROJECTIONS = {COLUMN_SHOP_NAME,COLUMN_AIRTIME,COLUMN_INVENTORY_NAME,
                                                                COLUMN_LATITUDE,COLUMN_lONGITUDE
                                                                };

//    public static final String[] DEFAULT_INVENTORY_PROJECTIONS = {COLUMN_CP_INVENTORY_ID,
//                                                                 COLUMN_AIRTIME,
//                                                                COLUMN_INTERNET,COLUMN_ELECTRIC,
//                                                                COLUMN_SHOPID};

    private static final String CREATE_TABLE_QUERY = " CREATE TABLE "+SHOP_TABLE_NAME+
            " ( "+COLUMN_CP_SHOP_ID+" integer primary key autoincrement,"
            +COLUMN_SHOP_ID+ " text, "
            +COLUMN_SHOP_NAME+"text not null"
            +COLUMN_INVENTORY_NAME+"tex not null"
            +COLUMN_LATITUDE+ " text not null)";



    private static final String DROP_TABLE_QUERY = "DROP TABLE IF EXISTS "+SHOP_TABLE_NAME;


    public static void onCreate(SQLiteDatabase database){
        //create a database/table
        database.execSQL(CREATE_TABLE_QUERY);
    }

    public static void onUpgrade(SQLiteDatabase database){
        //update the database/table
        database.execSQL(DROP_TABLE_QUERY);
        onCreate(database);
    }





}
